### ISSUE TITLE
Feature Request: Pull request number parameter

### ISSUE THREAD

**Issue by cquinones100** [aki77/delete-pr-comments-action#116]
Hello!

I would like to use this action to delete comments in a workflow that is triggered using workflow dispatch. The action can't find the PR number in this state, so I would like to explicitly pass in the PR number as a paramter.

I noticed that the action [currently attempts to retrieve the PR number from the context](https://github.com/aki77/delete-pr-comments-action/blob/7810f61f39c4533a567714607f29559081917944/src/main.ts#L17-L21). I am happy to make a PR to attempt to retrieve the pr number from `core.getInput('pullRequestNumber')`, too if that is ok.

Thanks!

**Comment by aki77** [comment]
PR welcome!

**Comment by cquinones100** [comment]
Great! I gave this a shot in https://github.com/aki77/delete-pr-comments-action/pull/117

**Comment by aki77** [comment]
Thanks.
Supported in v2.1.0!

https://github.com/aki77/delete-pr-comments-action/releases/tag/v2.1.0
