### ISSUE TITLE
Can't find `/build` comment

### ISSUE THREAD

**Issue by jmctune** [aki77/delete-pr-comments-action#82]
Hey there,

Thanks for this Github Action!

I can't seem to get this to work for me. I have a use case where I type `/build` a lot in a PR and would like to remove all comments that have `/build` in them within a PR.

Here's a minimum example:

```yaml
on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/build')
    steps:
      - name: Clean up build comments
        uses: aki77/delete-pr-comments-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyContains: |-
            /build
          noReply: 'true'
```

Here's the debug logs from the action:

```
 ##[debug]Evaluating condition for step: 'Clean up build comments'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Clean up build comments
##[debug]Loading inputs
##[debug]Evaluating: secrets.GITHUB_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'GITHUB_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run aki77/delete-pr-comments-action@v1
  with:
    token: ***
    bodyContains: /build
    noReply: true
  env:
    SHORT_SHA: b48da461
##[debug]bodyContains: ["/build"]
##[debug]Comment count: 0
##[debug]Comments: []
##[debug]Found 0 comments with match conditions.
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Clean up build comments
```

And a screenshot of me typing `/build` in my PR:

![image](https://github.com/aki77/delete-pr-comments-action/assets/17505625/f83a395b-97f8-4688-a7f3-36a951beea39)

Thanks for your help!

**Comment by aki77** [comment]
It seems to be failing in the retrieval of comments itself.
Is there a public repository where this can be reproduced?

https://github.com/aki77/delete-pr-comments-action/blob/main/src/main.ts#L29-L39

**Comment by jmreicha** [comment]
I just encountered this as well. Here is a reproduction PR (I want to remove any comment that contains `Preview`).

- https://github.com/jmreicha/kubernetes-infrastructure/pull/25

Here is the config and debug logs:

- https://github.com/jmreicha/kubernetes-infrastructure/blob/main/.github/workflows/diff.yaml#L91-L96
- https://github.com/jmreicha/kubernetes-infrastructure/actions/runs/7530776791/job/20498028366?pr=25

I know the token is good because I am using it later in the workflow and it works as expected.

**Comment by aki77** [comment]
If the problem reoccurs or if there are any new details that could help us address it, please feel free to reopen this issue or create a new one.

**Comment by aki77** [comment]
I understand.
The only thing this action supports is PR review comments.
PR review comments and issue comments are different for REST API.
Please refer to the following for more information.

https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#about-pull-request-review-comments
